### PR TITLE
Update orbit dependcy to available one

### PR DESCRIPTION
**Pull request by John-Holt-Tessella**
### Description of work

Update to orbit dependency that exists (closest one)

### Ticket

N/A

### Acceptance criteria

GUi builds

### Unit tests

-
### System tests

-

### Documentation

N/A
---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?
- [ ] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev)?

### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by FreddieAkeroyd** [comment]
Any particular reason you choose R20200224183213 over R20200529191137 ?

**Comment by FreddieAkeroyd** [comment]
I guess you chose 24/2 as it was closer to original 28/1 date. I don't know how it works, but looking at Notes column would suggest previous build was "2020-06 RC1" so should we use a  2020-06 long term release i.e. R20200529191137 ?

**Comment by FreddieAkeroyd** [comment]
Actually from a cached copy it looks like there was no RC before, S20200128200239 was 2020-03 M2 so R20200224183213 is then most appropriate

**Comment by John-Holt-Tessella** [comment]
@FreddieAkeroyd yes I chose the closest one (also tried the one after by mistake and it didn't work). I couldn't decide on what the R, S and I prefixes meant but you might be right.

**Pull request merged**
