### PR TITLE
Close the activeMQ connection on switch instrument.

### PR DESCRIPTION
**Pull request by John-Holt-Tessella**
### Description of work

ActiveMQ connections closed on switch instrument.

### To test

https://github.com/ISISComputingGroup/IBEX/issues/1806

### Acceptance criteria

When switching instruments activeMQ connections are not left open to old instruments. This is most clearly seen in debug view from the Eclipse IDE.

Test

* works with and without alarm perspective open. 
* number of alarms correctly reported

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Coding-Conventions)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit tests in place? Are the unit tests small and test the a class in isolation?
*I tried to put unit tests in place but it is impossible because the error is in BEAST and it is not written so I can do this*
- [x] Are there [system tests](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-RCPTT) in place? Do they test a minimal set of functionality and leave the gui as close as possible to its original state?
- [x] Did any existing system test break as a result of the current changes? 
- [ ] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
- [ ] Has the [manual system tests spreadsheet](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) been updated?

### Functional Tests

- [x] Do changes function as described? Add comments below that describe the tests performed.
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has developer documentation been updated if required?

### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by DominicOram** [comment]
The GUI isn't building as the alarms package hasn't been added to the required plugins for ui.menu (needed for AlarmConnectionCloser)

**Comment by DominicOram** [comment]
Once I've added the import this work. However, this isn't a very 'eclipsey' way of doing things. Rather it would be better to register an InstrumentInfoReceiver in the alarm plugin that does the closing whe the instrument is switched. This is already done in the alarm front end in AlarmSettings. Did you think about doing it this way?

**Comment by DominicOram** [comment]
Jenkins retest this please

**Comment by DominicOram** [comment]
Can you add a few more comments on the exact code in Alarms.java that switches the connection, it's hard to understand. Would you be able to use an Adapter to fix all the empty code blocks for pre/post startup? Now that you're an expert can you add a bit about the instrument switching somewhere on the dev manual.

**Comment by DominicOram** [comment]
A number of unit tests also appear to be failing in the build.

**Comment by John-Holt-Tessella** [comment]
I could maybe fix the empty code blocks but I am not sure how to do this easily. I could create a new extension point or create an optional point but I think that would be more complicated than the empty code blocks which at least it is obvious what is going on.

**Comment by John-Holt-Tessella** [comment]
I have put something (or am putting depending on when you read this) here: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Instrument%20switching

**Comment by DominicOram** [comment]
Apologies John, still a few issues:
* Consoles has undocumented constructor and unused field
* I have an exception on start-up: 
> Unable to update extended plugin for element named InstrumentInfoReceiver Plug-in uk.ac.stfc.isis.ibex.ui.alarm was unable to load class uk.ac.stfc.isis.ibex.ui.alarm.Alarms.
* I have an exception on start-up when pointing to another instrument:
> WARNING: JMS shutdown errorjava.lang.NullPointerException at org.csstudio.alarm.beast.ui.clientmodel.AlarmClientCommunicator.closeProducersAndConsumers(AlarmClientCommunicator.java:182)

**Pull request merged**
