### PR TITLE
Ticket2001 component delete info

### PR DESCRIPTION
**Pull request by ThomasLohnert**
### Description of work

Added feedback for the user when attempting to delete components that are in currently in use in configurations:
 - Added a dialog listing the dependencies preventing deletion of one or more components
 - Added a warning icon next to the name of the components in question in the selection dialog

### To test

https://github.com/ISISComputingGroup/IBEX/issues/2001

### Acceptance criteria

- Can delete components that are not in use. 
- Trying to delete one or more components that are used in configs results in an error dialog. 
- Component list gets updated correctly when adding/removing dependencies

---

#### Code Review

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Coding-Conventions)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit tests in place? Are the unit tests small and test the a class in isolation?
- [ ] Are there [system tests](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-RCPTT) in place? Do they test a minimal set of functionality and leave the gui as close as possible to its original state?
- [ ] Did any existing system test break as a result of the current changes? 
- [ ] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
- [ ] Has the [manual system tests spreadsheet](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) been updated?
- [ ] If an OPI has been modified, does it conform to the [style guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OPI-Creation)? There is a script called `check_opi_format.py` to help with this.

### Functional Tests

- [ ] Do changes function as described? Add comments below that describe the tests performed.
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has developer documentation been updated if required?

### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by AdrianPotter** [comment]
A number of classes have had their APIs (i.e. public methods) altered but no tests have been added. We should be more diligent about making sure that's done. Please could you review the changes and add unit tests as appropriate. Note that in some cases this might merit some rework of the API to allow for dependency injection.

**Comment by AdrianPotter** [comment]
Thanks @ThomasLohnert, the changes look great. We still don't have any tests for the ComponentDependenciesModel. Admittedly that's hard to unit test because it requires observers on the ConfigServer. Please could you instead add a system test.

**Comment by ThomasLohnert** [comment]
Good call as this change actually broke a lot of system tests due to changing the list widgets to single column tables. New system test and fixes for the old ones all in this PR: https://github.com/ISISComputingGroup/ibex_system_tests/pull/38

**Comment by DominicOram** [comment]
Looks good, I will hold off on merging until you have fixed the comments made in the system tests PR

**Pull request merged**
