### PR TITLE
Ticket1936: synoptic PV address validation in title

### PR DESCRIPTION
**Pull request by DominicOram**
### Description of work

Added the PV validation to the title bar rather than a separate label. See https://github.com/ISISComputingGroup/IBEX/issues/1936

Also merge: https://github.com/ISISComputingGroup/ibex_system_tests/pull/51

### To test

* Confirm new unit tests run
* Confirm that creating a PV with a bad address causes an error on the title bar
* Confirm this causes you to be unable to save
* Confirm that this persists when selecting new components
* Confirm that the component and pv name in the title bar get updated properly

---

#### Code Review

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Coding-Conventions)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit tests in place? Are the unit tests small and test the a class in isolation?
- [ ] Are there automated [system tests](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-RCPTT) in place? Do they test a minimal set of functionality and leave the gui as close as possible to its original state?
- [ ] Has the [manual system tests spreadsheet](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) been updated?
    - Manual system tests for the functionality should be added if there are no automated tests
    - Manual system tests can be removed from the template if they are covered by suitable automated tests
- [x] Did any existing system test break as a result of the current changes? 
- [x] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
- [x] If an OPI has been modified, does it conform to the [style guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OPI-Creation)? There is a script called `check_opi_format.py` to help with this.

### Functional Tests

- [x] Do changes function as described? Add comments below that describe the tests performed.
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has developer documentation been updated if required?
- [x] Have any new plugins been added to the appropriate feature.xml? You can check if this is needed by validating plugins as per method at  https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Common-Eclipse-Issues

### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by KathrynBaker** [comment]
Before moving to rework, there are no manual or system tests created for this change, was there a specific reason for not adding them? Otherwise, this is good to go.

**Comment by DominicOram** [comment]
Oops, sorry. I will add system tests, please put it back in ready.

**Comment by John-Holt-Tessella** [comment]
System tests added. Checks errors get put in bar. Errors themselves already look to be tested using unit tests.

**Comment by DominicOram** [comment]
@John-Holt-Tessella Thank you

**Pull request merged**
