### PR TITLE
Ticket 1282: Update checkstyle

### PR DESCRIPTION
**Pull request by DominicOram**
### Description of work

Updates the checkstyle as suggested on https://github.com/ISISComputingGroup/IBEX/issues/1282. Also took this opportunity to add some javadocs.

Also using this PR as a placeholder to test the new developer's Eclipse

### To test

Confirm that checkstyle warns about the issues listed in the original ticket.

To test the new developers Eclipse:
* Get it from \\olympic\babylon5\Scratch\Dominic Oram
* Using the eclipse version + workspace contained within the zip check that all expected plugins are there and are set up correctly (see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-the-IBEX-Developer-Version-of-Eclipse)

Once reviewed please add to \\isis\inst$\Kits$\CompGroup\ICP\Developer Tools

---

#### Code Review

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Coding-Conventions)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit tests in place? Are the unit tests small and test the a class in isolation?
- [ ] Are there [system tests](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-RCPTT) in place? Do they test a minimal set of functionality and leave the gui as close as possible to its original state?
- [ ] Did any existing system test break as a result of the current changes? 
- [ ] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
- [ ] Has the [manual system tests spreadsheet](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) been updated?

### Functional Tests

- [x] Do changes function as described? Add comments below that describe the tests performed.
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has developer documentation been updated if required?

### Final Steps
- [x] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by AdrianPotter** [comment]
Just tried to build with the new version of Eclipse. The product itself builds but I get the following build error:

```
Errors occurred during the build.
Errors running builder 'Checkstyle Builder' on project 'uk.ac.stfc.isis.ibex.instrument'.
Fileset from project "uk.ac.stfc.isis.ibex.instrument" has no valid check configuration.
Fileset from project "uk.ac.stfc.isis.ibex.instrument" has no valid check configuration.
...
Fileset from project "uk.ac.stfc.isis.ibex.validators.tests" has no valid check configuration.
Fileset from project "uk.ac.stfc.isis.ibex.validators.tests" has no valid check configuration.
```

Please could you investigate. Have I missed a step?

**Comment by DominicOram** [comment]
New version should not give build errors any more. I've also added Eclipse checkstyle highlighting to all non-test projects as part of this ticket.

Note that as this ticket creates a stricter checkstyle there are now more warnings in Jenkins, causing an unstable build. To fix this you will need to increase the number of warnings Jenkins allows before failing.

**Comment by AdrianPotter** [comment]
Checkstyle plugin in still complaining about not being able to find RedundantThrows as part of Treewalker. RedundantThrows was removed at checkstyle 6.2 but it's not clear why we're still looking for it as it's not in the checkstyle.xml

**Comment by KathrynBaker** [comment]
There are two Checkstyle.xmls to consider, one is the one we were using, part of this was to update to the one that is being used by Jenkins – which is in another area, and was meant to be moved to by this ticket (so that we could use Checkstyle more readily to fix these warnings) – has the correct Checkstyle been updated?

**Comment by DominicOram** [comment]
Yes, both now use uk.ac.stfc.isis.ibex.client.tycho.parent/checkstyle.xml.

At least that's the one referenced in both the POM and in Eclipse settings. Is this the two places you meant?

**Comment by KathrynBaker** [comment]
That’s right, everything should be matching and OK then.

**Comment by DominicOram** [comment]
Ok, 3rd time lucky. Can you try the version that is on Scratch now?

**Pull request merged**
