### PR TITLE
Ticket8106_use_IBEXButtonFactory_to_create_generic_buttons

### PR DESCRIPTION
**Pull request by isaachilly**
### Description of work

Create a button builder for buttons used in the perspectives.
Converted a few buttons over to using this new builder however ticket created to continue this converting.

### Ticket

- https://github.com/ISISComputingGroup/IBEX/issues/8106

### Acceptance criteria

*List the acceptance criteria for the PR. The aim is provide information to help the reviewer*

### Unit tests

*Give an overview of unit tests you have added or modified, if applicable. The aim is provide information to help the reviewer*

### System tests

*Mention any automated tests or manual tests that you have added or modified, if applicable. The aim is provide information to help the reviewer*

### Documentation
*Highlight and provide a link to any additions or changes to the documentation, if applicable. The aim is provide information to help the reviewer*

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] If the change is to an OPI, does the `check_opi_format.py` script in [C:\Instrument\Dev\ibex_gui\base\uk.ac.stfc.isis.ibex.opis](https://github.com/ISISComputingGroup/ibex_gui/blob/master/base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py) pass?
- [ ] Do the changes function as described and is it robust?
- [ ] Is there associated PR for the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)?

### Final Steps
- [ ] Reviewer has also merged the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)

### CODE REVIEW

**Comment by Chsudeepta** [comment]
1. Get rid of unused imports by pressing - CTRL+SHIFT+O in eclipse. This will get rid of the checkstyle issues.
2. Use parametrised constructor for the builder to ensure that anytime a button is required mandatory fields are already set. These are parent and buttonstyle.
	public IBEXButtonBuilder(final Composite parent, final Integer buttonStyle) {
		this.parent = parent;
		this.buttonStyle = buttonStyle;
	}
3. If you want to avoid errors in consuming files due to point 2 above, you can add a public default constructor temporarily. Remove this after you are done with changes to all the callers.

**Review by Chsudeepta — APPROVED** [review]

**Review by Chsudeepta — APPROVED** [review]

**Comment by isaachilly** [comment]
Which tickets? I accidentally merged master as you can see in the commit history but I then reverted it and the only changes I can see with the PR are the ones associated with the ticket.

**Comment by isaachilly** [comment]
Oh I see yes. Confused how I've managed to do that, I thought I reverted fine just reset to before the merge last commit. Only thing I can think of is I merged master into the branch but then it counted the revert (that was removing the master changes) as not an inverse and has thought that is part of the commit history etc that I deleted them not reverted them.

**Comment by isaachilly** [comment]
Okay, I understand, my fault completely. I should've remembered how git works underneath. Yes let me know what I can do to help.

**Pull request merged**
