### PR TITLE
Ticket1432 motors colour blind

### PR DESCRIPTION
**Pull request by IsabellaRey**
### Description of work

- Added a preferences menu to allow users to choose between two modes; "normal vision" and "colour blind"
- Changed the background colour of the individual motors within the ToM to reflect the users's choice in the menu.
- We have kept the two greys the same, as they were already very similar in normal vision mode.
- Setting isn't persisted between sessions, see comment in ticket itself.
- The new colours have been checked using colouroracle for the main two types of colour-blindness and appear to be fine for colour-blind users.
- Added a manual system test to the spreadsheet.

### To test

ISISComputingGroup/IBEX#1432

### Acceptance criteria

- Start the motors IOC (galil) in simulation mode.
- Start up the motors view.
- Switch between the two colour options in the menu and see that the motors view gets updated.
- Also try restarting the GUI and changing the colour options before opening the motors perspective.
- Test that the new colour combinations are suitable for colour-blind users. Set the colour scheme to colour blind, set one of the motors moving, take a screenshot and check using colouroracle that the colours are distinguishable. (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Designing-for-Colour-Blindness)

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Coding-Conventions)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit tests in place? Are the unit tests small and test the a class in isolation?
- [ ] Are there [system tests](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-RCPTT) in place? Do they test a minimal set of functionality and leave the gui as close as possible to its original state?
- [ ] Did any existing system test break as a result of the current changes? 
- [x] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
- [x] Has the [manual system tests spreadsheet](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) been updated?

### Functional Tests

- [x] Do changes function as described? Add comments below that describe the tests performed.
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has developer documentation been updated if required?

### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by kjwoodsISIS** [comment]
Does the menu actually say "Normal Vision" and "Colour Blind"?  Might it be better to choose something other than "Colour Blind" (although I can't think of an alternative at the moment).

**Comment by KathrynBaker** [comment]
If it does say Colour Blind, we should change it, as there are different types of colour blindness, and what works for one might not necessarily work for another. Perhaps just calling it a “Standard Colour Scheme” and “Alternative Colour Scheme 1” would be better – even if it does take longer to say.

Regards,
Kathryn

**Comment by ThomasLohnert** [comment]
How about something like "Default Scheme" / "High Contrast Scheme" to be a bit more descriptive?

**Comment by KathrynBaker** [comment]
If it is a high contrast scheme yes, but high contrast is fairly specific, and relates to the relative brightness of the colours, so unless we actually have a high contrast scheme using that phrase would be misleading for those that need the difference. So white and black, whichever way round you deal with them are always high contrast. For example there is quite a bit of background on https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html. I can’t find them now, but W3C used to have some equations to define the contrast ratings (I think it has changed the policy since I looked at it), which is what I used to choose quite the shade of red we use on the perspective buttons for the alarms and logs when they are in their highlighted state. So if the contrast is appropriate, then the phrase is fine, I haven’t looked at the actual values chosen to be able to tell.

**Comment by DominicOram** [comment]
I agree with the comments above renaming the menu item. Can you also move the colors in DisplayPreferences into a separate Enum so that we can add more down the line? Also, if you feel like you have time now might be a good opportunity to change the MinimalMotorView to using a ViewModel.

**Comment by IsabellaRey** [comment]
Items addressed:

- Menu items renamed to "Standard Colour Scheme" and "Alternative Colour Scheme 1"

- After discussion we decided to leave the DisplayPreferences class as is, because it's not clear yet how this is going to evolve in the future: the DisplayPreferences class contains things that are specific to the motor, whereas the ColourOption enum could potentially be extracted in a separate plugin if other parts of the GUI need to react to the user's colour scheme selection

- Refactoring addressed in ISISComputingGroup/IBEX#1902, as a first exercise for @Tom-Willemsen on view models

**Pull request merged**
