### PR TITLE
Ticket2273 groups should be orderable

### PR DESCRIPTION
**Pull request by AdrianPotter**
### Description of work

Preserve the order of groups as set in the configuration editor, including component groups

### To test

https://github.com/ISISComputingGroup/IBEX/issues/2273

### Acceptance criteria

Before starting, create a component with at least 2 groups

-  [x] Create a config, add the component. Verify that the component groups appear in the config when it is saved
- [x] Edit the component, delete one of the groups. Verify it is removed from the config
- [x] Edit the config, verify none of the unused group blocks can be added to the config group
- [x] Edit the config, move the component group around in the group ordering. Save the group, verify that the group order is reflected in the block display
- [x] Restart the GUI, check that the group ordering is preserved
- [x] Remove the component from the config, verify that the component group is removed from the config

---

#### Code Review

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Coding-Conventions)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit tests in place? Are the unit tests small and test the a class in isolation?
- [x] Are there automated [system tests](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-RCPTT) in place? Do they test a minimal set of functionality and leave the gui as close as possible to its original state?
- [ ] Has the [manual system tests spreadsheet](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) been updated?
    - Manual system tests for the functionality should be added if there are no automated tests
    - Manual system tests can be removed from the template if they are covered by suitable automated tests
- [ ] Did any existing system test break as a result of the current changes? 
- [x] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
- [ ] If an OPI has been modified, does it conform to the [style guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OPI-Creation)? There is a script called `check_opi_format.py` to help with this.

### Functional Tests

- [x] Do changes function as described? Add comments below that describe the tests performed.
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has developer documentation been updated if required?
- [x] Have any new plugins been added to the appropriate feature.xml? You can check if this is needed by validating plugins as per method at  https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Common-Eclipse-Issues

### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by AdrianPotter** [comment]
> I can not add a block to a group which comes from a component. Should I be able to?

No. You can't do that now.

> If my block is in a component which shares group name with one in a config it appears I can take the block out of the group. Also having taken the block out the config losses its component xml attribute

Existing behaviour on master

**Comment by AdrianPotter** [comment]
System tests added for both fixed bits of behaviour

**Comment by DominicOram** [comment]
Manual tests confirm above fixed. In general seems to work well, couple of issues in the system tests.

**Comment by AdrianPotter** [comment]
I've fixed those tests and rerun them. Everything seems fine now

**Pull request merged**
