### PR TITLE
Changed the motor details OPI.

### PR DESCRIPTION
**Pull request by RichardTysonIsis**
### Description of work

This is a pull request that changed the motor details OPI as required by several different tickets.
For [#3344](https://github.com/ISISComputingGroup/IBEX/issues/3344):
- I changed the style of the OPI to the new style. The layout is mainly the same although I added a button to return to the motor overview, I changed a yellow rectangle that appeared upon a soft limit violation to a LED and I moved the messages displayed upon certain actions to their own container. The OPI is now a bit bigger, I could make it smaller but I think it's a lot nicer like this.

For [#1890](https://github.com/ISISComputingGroup/IBEX/issues/1890): 
- The units will now be displayed in the same value box that displays the value of the PV. I think this is better firstly because these units come directly from the IOC and are therefore more trust worthy. The consistent  labelling will also avoid the errors mentioned in 1890, and it looks a lot nicer. Finally, changing the value in the "EG" input box will change the units displayed (although you will need to refresh the OPI).

For [#3300](https://github.com/ISISComputingGroup/IBEX/issues/3300):
- I changed the SPMG buttons to a set of radio buttons.

For [#3295](https://github.com/ISISComputingGroup/IBEX/issues/3295):
-  I added a STOP button that will STOP the motor.

Finally, I wrote a script (linked to an invisible text update) that will close the motor details page and open the motor overview page if manager mode is exited. This is part of another ticket, [#3355](https://github.com/ISISComputingGroup/IBEX/issues/3355) but is not the entirety of the ticket (I added it here though because I thought it'd be good for consistency and also because now fixing the ticket will be easy once we find what other protected OPIs exist and where they are called). This may cause a bug in the console, but it is not recurrent (I only saw it once) so I'm not sure how to reproduce it.

**Note1**: I left the old version of the details OPI for the reviewer to compare the two OPIs, as there is quite a lot to compare. Please feel free to delete, or I'll be happy to do it myself.
**Note2**: I've added a note in the release notes for each of the tickets.
**Note3**: I've assigned myself to all the relevant tickets and these can all be moved to the "review complete" column once this pull request is merged.

### Tickets

https://github.com/ISISComputingGroup/IBEX/issues/3344
https://github.com/ISISComputingGroup/IBEX/issues/1890
https://github.com/ISISComputingGroup/IBEX/issues/3300
https://github.com/ISISComputingGroup/IBEX/issues/3295

### Acceptance criteria

- There is a new style OPI for the motor details.
- The new OPI has all the functionality of the old one.
- The new OPI is aesthetically pleasing.
- The units are displayed in an adequate and readable manner.
- The units can be updated by changing the EGU value.
- The state of the Motor Record "Command" feature is made obvious by an appropriate choice of GUI control which works just like the SPMG choice button.
- A STOP button is clearly positioned on the detailed Motor OPI.
- The STOP button should have a red background, with the text "STOP" in yellow.
- The motor overview is opened when manager mode is closed.

### Unit tests

None required.

### System tests

None required.

### Documentation
None found.

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?
- [ ] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev)?

### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by DominicOram** [comment]
Can you add a screenshot of the new view to this ticket? Then @IainJohnson can confirm if it fits his requirements.

**Comment by RichardTysonIsis** [comment]
motor_details_opi

**Comment by IainJohnson** [comment]
Hello @RichardTysonIsis @DominicOram looks good, the radio buttons are great. What do the Enable/Disable buttons do?

**Comment by DominicOram** [comment]
From a quick look at the code I think it just disables any puts to the motor. I think we may have used it in the past for things like the EMMA chopper lifter where you don't want to talk to the underlying motor in general. Did you also want some LEDs on this panel for at home etc?

**Comment by ThomasLohnert** [comment]
Mockup for suggested layout changes:
alignment

**Comment by RichardTysonIsis** [comment]
The latest commit changed th OPI following Thomas' advice and created a new style OPI for the MSTA details. I added a "Return to Motor Details" button to it. I also merged master into the branch so that it's under E4.

**Comment by ThomasLohnert** [comment]
Looks a lot neater, thanks!
As discussed, after having another think about it please change the soft limit violation indicator to just pop up as a larger warning text in the "Drive" group (the highlight box is not ideal as you can trigger the softlimit violation from any widget that makes the motor move, not just `MoveAbs`) and get rid of the LED in the right column - I don't think this is noticeable enough

**Pull request merged**
