### PR TITLE
Add option to clear target details when we change type

### PR DESCRIPTION
**Pull request by AdrianPotter**
### Description of work

I've set the target details of the current component to clear when creating/editing a new synoptic and the type of the component is changed. This means that the target details will always switch to the default when the component type is changed. Under the previous behaviour, it only occurred on the first change.

I've added a manual system test for the synoptics

### To test

https://github.com/ISISComputingGroup/IBEX/issues/1602

### Acceptance criteria

When the component type of a synoptic is changed, the target details switch to default

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Coding-Conventions)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit tests in place? Are the unit tests small and test the a class in isolation?
- [ ] Are there [system tests](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-RCPTT) in place? Do they test a minimal set of functionality and leave the gui as close as possible to its original state?
- [ ] Did any existing system test break as a result of the current changes? 
- [ ] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
- [ ] Has the [manual system tests spreadsheet](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) been updated?

### Functional Tests

- [ ] Do changes function as described? Add comments below that describe the tests performed.
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has developer documentation been updated if required?

### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by John-Holt-Tessella** [comment]
Null Pointer Exception

1. Select component detail Analyser
1. Select Lakeshore

I think this is trying to open the select 1 out of 2 possibilities box. Think about the behaviour for this. Do a  paper prototype with the task of selecting Lakeshore 218; does the user find this natural or should it be listed as Lakeshore (218) AND lakeshore (336)?

**Comment by John-Holt-Tessella** [comment]
Is this the right behaviour. If I fill in macros then decide I want to classify it differently and change my component details I will loose all my macros and have to retype them. Is this correct? It might be better to change this only if it was a default choice. An indicator to suggest the mismatch might be good.

**Comment by John-Holt-Tessella** [comment]
Will review fully after changes and questions.

**Comment by DominicOram** [comment]
Just an FYI to keep an eye on https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket858_multi_pvs_in_synoptic_bug whilst doing this work as it contains quite a bit of refactoring of the editor.

**Comment by AdrianPotter** [comment]
Closing PR for now. Revisit at a later date

**Pull request closed without merging**
