### PR TITLE
DAE experiment setup enhancements

### PR DESCRIPTION
**Pull request by ThomasLohnert**
### Description of work

(Forgot to switch branch after branching 1541 off of 1551 so this contains changes for both tickets)

1541:
Added labels to readback and selection widgets for time channel file, period file and DAE tables for better clarity.

1551:
Changed layout of the period settings tab so that the content changes based on 1) period type and 2) period source to show/enable only the relevant settings.
### To test

https://github.com/ISISComputingGroup/IBEX/issues/1551
https://github.com/ISISComputingGroup/IBEX/issues/1541
### Acceptance criteria

File selection controls in DAE are unambiguous and visually appealing.

Period tab content changes to show settings relevant to selected period type / source and retains these settings (once applied). Layout is clear and visually appealing.

---
#### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Coding-Conventions)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit tests in place? Are the unit tests small and test the a class in isolation?
- [x] Are there [system tests](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-RCPTT) in place? Do they test a minimal set of functionality and leave the gui as close as possible to its original state?
- [x] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed.
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has developer documentation been updated if required?
### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by DominicOram** [comment]
Looks good, reacts really well to user input. A couple of improvements:
* Can you move the logic of the updateWindow() method into the ViewModel?
* It is possible to select the blank input in the drop down, as well as select the message that tells me if no files are found. Although it's not completely part of this ticket can you look at this?
* When no files are found the error says to look in the an [instrument name] folder. Can it instead actually specify the correct folder?
* Add the changes to release notes

**Comment by DominicOram** [comment]
Cool, a couple of other things, sorry to be a pain.
* DataAcq...ViewModel and PeriodsViewModel both have the code for creating the none found error string and the binding for the instrument name. Can we move this into a shared class (especially as if we later change the config path it currently means changing in 5/6 seperate places)
* Can you do some error handling on the instrument name being disconnected?
* Minor nit pick - its probably better to pass around Composites in the PeriodsPanel rather than Controls

**Comment by DominicOram** [comment]
Much nicer, thanks. Can you add a system test for the logic of how the view changes with different period selections?

**Comment by ThomasLohnert** [comment]
Fixed DAEExperimentTabsAreDisabledIfRunning system test on branch https://github.com/ISISComputingGroup/ibex_system_tests/pull/29

**Comment by IsabellaRey** [comment]
I've done Approve changes, but haven't actually checked the rework. It was just to un-block the review so others can pick it up

**Pull request merged**
