### PR TITLE
Added SANS2D waveguide OPI

### PR DESCRIPTION
**Pull request by RaiBishal**
### Description of work

Added SANS2D waveguide OPI

### Ticket

https://github.com/ISISComputingGroup/IBEX/issues/4575

### Acceptance criteria

1. The Waveguide Position Controls appears only on the "advanced" tab of the IBEX GUI.
1. Motion is disabled/enabled if the PLC inhibit signal is on/off.
1. If motion is enabled, 
   1. I can move each moveable waveguide to any position in its range via the IBEX GUI
      * there should be one position control per waveguide (to allow each waveguide to be moved independently of the others)
   1. Each waveguide position control should:
      1. allow the user to define the position setpoint of the waveguide
      1. reflect the position of the waveguide in a readback field
   1. I can move each moveable waveguide to any position in its range via genie_python
1. If motion is disabled, I am unable to move any waveguide (the waveguide position control is disabled)
      * the Waveguide Position Controls should be greyed out when motion is inhibited
      * genie_python should report that it cannot move the relevant axis. 
1. The "advanced" tab OPI provides a "Move All" button (c.f. Reflectometry), so that I can enter all the positions of the guides (& apertures - see #4574)  and make sure they are correct before anything moves.
1. IBEX provides the same level of functionality as the existing LabVIEW VIs

Note: Currently motion cannot be enabled/disabled as we do not have PV available for it. Also, the setpoint is automatically set when the spinner is used to set a value.
The rules set to control the movement of the waveguide, points to Galil controller 1 motor 4.

### Unit tests

*Give an overview of unit tests you have added or modified, if applicable. The aim is provide information to help the reviewer*

### System tests

*Mention any automated tests or manual tests that you have added or modified, if applicable. The aim is provide information to help the reviewer*

### Documentation
*Highlight and provide a link to any additions or changes to the documentation, if applicable. The aim is provide information to help the reviewer*

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?
- [ ] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev)?

### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by Alistair-McGann-Tessella** [comment]
Feedback:
General:
* No icon
* I'm worried the vacuum and motion LEDs could be confusing because they can be interpreted in different ways. Can you change the labels to read 'vacuum on' and 'motion enabled'? Or you could add an extra text box which could read 'enabled/disabled' for the motor and 'on/off' for the vacuum.

User tab:
* The name of the grouping container has defaulted to 'Grouping container'
* Position selector should have a text label saying 'Preset Positions' or similar.
* Position selector should be a drop-down box instead of a text box. This will be like a motion set point where the user can choose a known position that is useful.

Advanced tab:
* There are two containers labelled 'Guide 1'

Individual waveguide:
* There is no way of changing the motor for each individual waveguide
* The text label should show the wave guide number (from $(NUMBER)?) instead of just 'Guide:'.
* The graphic represantation should have a bounding box to make it clearer where it's at the top or bottom.

The mockup and labview VIs have all of the waveguides in a line. I think this is a tool to help the instrument scientist see the state of the wavegudes (and apertures) at a glance. To implement this, my suggestions are:
* Line up the guide controls instead of having them in a grid pattern. This is also in the mockup on the ICPDiscussions site
* Add 'front' and 'back' labels by the front and rearmost guides
* The setpoint, readback and move controls should be below the graphic, so the graphics can line up uninterrupted

**Comment by kjwoodsISIS** [comment]
@Alistair-McGann-Tessella & @RaiBishal - can we chat about Alistair's comments on the UI.

**Comment by Alistair-McGann-Tessella** [comment]
Feedback:
The OPI is looking much better, all of the UI elements are looking really good and how you would 'expect'. There are a few fixes just to tie all the elements together and make them work correctly. 

* The motor addresses (e.g. MTR0101) are hard-coded for each aperture or waveguide. Have these addresses come from how SANS2D is set up? It might be worthwhile to add these as OPI macros for each waveguide or aperture, so we wouldn't have to change a value in the OPI if a motor switches axis or crates.
* The PV names have hard-coded instrument names to TE:NDLT1205. These should be replaced with $(P) so it points to the instrument it is running on.
* The controls (e.g. motor setpoints) apply the new setpoints as soon as the input is changed, instead of waiting for the user to press the move motor button.
    * In the motor extensions you should add a `:SPNOACTION` as a holding cell, with a calc record to write to hardware
* Can you make another linking container for the apertures?  This should look very similar to the waveguide OPI you have already, but with only a single gap instead of the aperture

* The first waveguide/aperture control box does is not a linking container like the others, this may be fixed with a dedicated aperture control box?
* Can you use an LED and a label to indicate the motion and vacuum statuses?
* The OPI might be too tall, my 'waveguide' label is hidden off the top of the screen. (This might be an issue with my high-dpi display, though)
* I found a waveguide graphic hiding behind the tabbed grouping container which should be moved or removed

Most of these fixes should be straightforward, but CSS is notoriously fiddly so please grab someone to point you in the right places. And please let me know if I can clarify something

**Comment by John-Holt-Tessella** [comment]
Updated feedback above (just happened to see it).

**Comment by RaiBishal** [comment]
> * Can you connect a PV to the vacuum and motion indicators so they change depending on the state of the system? I think the vacuum system uses a text label with a changing background colour

Could this possibly be a part of this ticket [#4570](https://github.com/ISISComputingGroup/IBEX/issues/4570)? Since we have already dragged ticket [#4574](https://github.com/ISISComputingGroup/IBEX/issues/4574) in this ticket as well. I think it would be better to keep  [#4570](https://github.com/ISISComputingGroup/IBEX/issues/4570) separate.

**Comment by RaiBishal** [comment]
Nevermind the above comment.

**Comment by DominicOram** [comment]
> The controls (e.g. motor setpoints) apply the new setpoints as soon as the input is changed, instead of waiting for the user to press the move motor button.

> In the motor extensions you should add a :SP_NO_ACTION as a holding cell, with a calc record to write to hardware (see pattern in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/ISIS-PV-Guide)

Sorry to jump in here but given that:
* This PR is now over a month old
* This ticket is holding up 4 others in the EPIC
* The delayed action is a non-negligible bit of logic that should be written in a generic way given that it's been requested on multiple beamlines

I think we should pull this functionality into a separate ticket.

**Comment by DominicOram** [comment]
New ticket is at https://github.com/ISISComputingGroup/IBEX/issues/5499

**Comment by RaiBishal** [comment]
> The motor addresses (e.g. MTR0101) are hard-coded for each aperture or waveguide. Have these addresses come from how SANS2D is set up? It might be worthwhile to add these as OPI macros for each waveguide or aperture, so we wouldn't have to change a value in the OPI if a motor switches axis or crates.
> 
> * [JH] we would prefer not to make people fill in macros for this but ideally code the OPI to an axis which is sitting on a motor.

As per John's suggestion, coding OPI to an axis would be ideal however, we do not have mechanism for setting the specific position of apertures or waveguide. This will need to done after https://github.com/ISISComputingGroup/IBEX/issues/5499 is completed.

**Comment by DominicOram** [comment]
Also, given https://github.com/ISISComputingGroup/IBEX/issues/5499#issuecomment-648261738 can we remove the `Move All` and individual `Move` buttons for now?

**Comment by kjwoodsISIS** [comment]
@RaiBishal - when you have completed the rework, can you give me a demo of the Aperture & Guides control panel.  Thanks.

**Comment by RaiBishal** [comment]
> @RaiBishal - when you have completed the rework, can you give me a demo of the Aperture & Guides control panel. Thanks.

Sure

**Comment by RaiBishal** [comment]
After discussing with @DominicOram, a new ticket is to be introduced to figure out and implement the best way to set the high and low limit for the Apertures and guides. Currently, this done by OPI macro and this is not the ideal way.


Ticket:  https://github.com/ISISComputingGroup/IBEX/issues/5523

**Pull request merged**
