### PR TITLE
Ticket873: Added show/hide block to right clicking a group

### PR DESCRIPTION
**Pull request by DominicOram**
### Description of work

Fixes https://github.com/ISISComputingGroup/IBEX/issues/873.

### To test

* Right click on group view but outside a group, confirm that show/hide blocks appears and works
* Right click on white space in a group, confirm that show/hide blocks appears and works
* Right click on a block, confirm that no new menu appears.
* Confirm that when blocks are shown/hidden the right click menu changes appropriately

---

#### Code Review

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Coding-Conventions)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit tests in place? Are the unit tests small and test the a class in isolation?
- [ ] Are there [system tests](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-RCPTT) in place? Do they test a minimal set of functionality and leave the gui as close as possible to its original state?
- [x] Did any existing system test break as a result of the current changes? 
- [x] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
- [ ] Has the [manual system tests spreadsheet](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) been updated?

### Functional Tests

- [x] Do changes function as described? Add comments below that describe the tests performed.
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has developer documentation been updated if required?

### Final Steps
- [x] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by AdrianPotter** [comment]
As just discussed please could you:

-  [ ] Expand the range where right clicking brings up the show/hide popup to include the group title (it's where I naively first clicked!
- [ ] Include the show/hide option when right clicking on a block (still applies at a group level)

**Comment by DominicOram** [comment]
Added in suggestions, confirm that order in menu is as expected

**Comment by AdrianPotter** [comment]
Works great, thanks. Just the usual things:

- [ ] Please add to release notes
- [ ] Please add appropriate manual system tests

**Comment by DominicOram** [comment]
Added 21-25 & 21-26

**Pull request merged**
