### PR TITLE
Ticket1238 zoom sample stack

### PR DESCRIPTION
**Pull request by Tom-Willemsen**
### Description of work

Create an IOC and axes file for the ZOOM sample stack.

### To test

https://github.com/ISISComputingGroup/IBEX/issues/1238

### Acceptance criteria

- [x] There is an OPI suitable for the zoom sample stack
- [x] There are suitable screens showing the details of the various motors when you press the "motor details" buttons
- [x] The "view sample changer" button is disabled (we don't know precisely what the sample changer will be yet).

The axes are defined in the following file `Instrument/Settings/config/NDWxxxx/configurations/galil/axes.cmd`, which should contain the following:

```
$(IFDMC01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:X,mAXIS=MTR0101")
$(IFDMC01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:Y,mAXIS=MTR0102")
$(IFDMC01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:ZHI,mAXIS=MTR0103")
$(IFDMC01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:THETA,mAXIS=MTR0104")
$(IFDMC01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:PSI,mAXIS=MTR0105")
$(IFDMC01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:CHI,mAXIS=MTR0106")
$(IFDMC01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:ZLO,mAXIS=MTR0107")
$(IFDMC02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:XRAIL,mAXIS=MTR0201")
$(IFDMC02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:YRAIL,mAXIS=MTR0202")
```

When checking the OPIs using `check_opi_format.py`, the script will come up with two errors because "Top" and "Bottom" do not end with colons. In this case they do not need to end with colons so the warnings can be ignored.

I copied the Sample PV (`%MYPVPREFIX%LKUP:SAMPLE:POSN`) from another OPI - this may need correcting once we know exactly what the sample changer is.

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Coding-Conventions)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit tests in place? Are the unit tests small and test the a class in isolation?
- [ ] Are there [system tests](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-RCPTT) in place? Do they test a minimal set of functionality and leave the gui as close as possible to its original state?
- [ ] Did any existing system test break as a result of the current changes? 
- [ ] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
- [ ] Has the [manual system tests spreadsheet](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) been updated?
- [ ] If an OPI has been modified, does it conform to the [style guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OPI-Creation)? There is a script called `check_opi_format.py` to help with this.

### Functional Tests

- [ ] Do changes function as described? Add comments below that describe the tests performed.
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has developer documentation been updated if required?

### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by AdrianPotter** [comment]
- [ ] Please could the axis setup be documented somewhere in the Wiki, connected to the Zoom instrument (e.g. https://github.com/ISISComputingGroup/IBEX/wiki/ZOOM-Instrument-Details#noteJJXray)
- [ ] The axis configuration above does not contain a definition for the STACK:X axis, I presume `$(IFDMC01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:X,mAXIS=MTR0101")` has just been omitted accidentally?

**Comment by KathrynBaker** [comment]
The x won’t have been included at this point as that will be a Beckhoff axis in read only mode, so as yet not something that can be integrated easily

**Comment by AdrianPotter** [comment]
- [ ] There's a note above about the `LKUP:SAMPLE:POSN'. Please could you elaborate on how this connects into the OPI. Is this a separate motor?

**Comment by Tom-Willemsen** [comment]
`LKUP:SAMPLE:POSN` is part of the sample changer. Last time I checked, we didn't know the details of which sample changer will be used, so this is essentially a placeholder PV until we know what the real sample changer will be.

The reason I called it `LKUP:SAMPLE:POSN` was because that's what it is called on the LARMOR sample stack. If they happen to use the same sample changer it might (?) work, but the likelihood is that it'll need changing once we know the details.

It's included on this OPI because Kevin provided a sketch of what the OPI should look like, and this was on it.

**Comment by AdrianPotter** [comment]
- [ ] I'm confused which is the Beckhoff and which is the Galil. In the OPI `XRAIL` is read only (at least it has no box for the set point) so I assumed that was the Beckhoff, yet it is defined in `axes.cmd` as connecting to one of the Galils. `STACK:X` on the other hand isn't defined in the `axes.cmd` above and yet it has a writable set point. Please clarify.

**Comment by KathrynBaker** [comment]
Now I’m confused as well, the sample stack will have an x as standard, and there is an extra x which is the beckhoff. I missed the fact that there was something called XRAIL as well – which will be the beckhoff.

**Comment by Tom-Willemsen** [comment]
Hi @KathrynBaker ,

The confusion is due to my mistake. The `axes.cmd` file should look like this (I accidentally missed the first line when I copied it over):
```
$(IFDMC01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:X,mAXIS=MTR0101")
$(IFDMC01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:Y,mAXIS=MTR0102")
$(IFDMC01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:ZHI,mAXIS=MTR0103")
$(IFDMC01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:THETA,mAXIS=MTR0104")
$(IFDMC01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:PSI,mAXIS=MTR0105")
$(IFDMC01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:CHI,mAXIS=MTR0106")
$(IFDMC01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:ZLO,mAXIS=MTR0107")
$(IFDMC02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:XRAIL,mAXIS=MTR0201")
$(IFDMC02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=STACK:YRAIL,mAXIS=MTR0202")
```

The `XRAIL` and `YRAIL` PVs correspond to the movement along and across the rails. 

For the purposes of the current OPI I'm pretending that the Beckhoff can be read in the same way as a Galil (pending further information).

Hope that helps? If not feel free to come and have a chat...

**Comment by Tom-Willemsen** [comment]
Hi Adrian,

I've done the changes you suggested.

After a short conversation with @KathrynBaker this morning, I've removed the PV which pointed at the sample changer and created a ticket to update the OPI when we have some details about it (Ticket 2042).

I've edited the wiki page you linked to slightly to make it a bit more readable, but I haven't added any information about the sample changer because we don't know what it is yet. I will add a note to update the documentation as part of Ticket 2042.

**Pull request merged**
