### PR TITLE
Ticket 1932: Disable synoptic menu

### PR DESCRIPTION
**Pull request by DominicOram**
### Description of work

A bit of a fudge to force the menu to check for enabled at startup of GUI.

### To test

https://github.com/ISISComputingGroup/IBEX/issues/1932

---

#### Code Review

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Coding-Conventions)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit tests in place? Are the unit tests small and test the a class in isolation?
- [x] Are there [system tests](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-RCPTT) in place? Do they test a minimal set of functionality and leave the gui as close as possible to its original state?
- [x] Did any existing system test break as a result of the current changes? 
- [x] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
- [x] Has the [manual system tests spreadsheet](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) been updated?

### Functional Tests

- [x] Do changes function as described? Add comments below that describe the tests performed.
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has developer documentation been updated if required?

### Final Steps
- [x] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by Tom-Willemsen** [comment]
I'm getting the following exception in the console when running this:

!MESSAGE Plug-in "uk.ac.stfc.isis.ibex.ui.synoptic.editor" was unable to instantiate class "uk.ac.stfc.isis.ibex.ui.synoptic.editor.commands.NOP".
!STACK 0
java.lang.InstantiationException: uk.ac.stfc.isis.ibex.ui.synoptic.editor.commands.NOP
	at java.lang.Class.newInstance(Unknown Source)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	[snip]
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
Caused by: java.lang.NoSuchMethodException: uk.ac.stfc.isis.ibex.ui.synoptic.editor.commands.NOP.<init>()
	at java.lang.Class.getConstructor0(Unknown Source)
	... 52 more

**Comment by DominicOram** [comment]
Apologies, didn't add a proper constructor, try again now?

**Comment by Tom-Willemsen** [comment]
Will merge once system test is added and checkstyle warning fixed

**Comment by DominicOram** [comment]
Tests 31-1,2,3 have been added

**Pull request merged**
