### PR TITLE
Ticket369: Add keyboard shortcuts for perspectives

### PR DESCRIPTION
**Pull request by DominicOram**
### Description of work

Adds shortcuts for all visible perspectives on the function keys.

### To test

See https://github.com/ISISComputingGroup/IBEX/issues/369

Confirm that all visible perspectives can be switched to using the function keys. Ensure this still works when your client has non-default perspectives available.

Added manual test 27-1 & 27-2

---

#### Code Review

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Coding-Conventions)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit tests in place? Are the unit tests small and test the a class in isolation?
_hard to unit test due to use of extension points_
- [ ] Are there [system tests](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-RCPTT) in place? Do they test a minimal set of functionality and leave the gui as close as possible to its original state?
- [ ] Did any existing system test break as a result of the current changes? 
- [ ] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
- [ ] Has the [manual system tests spreadsheet](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) been updated?

### Functional Tests

- [x] Do changes function as described? Add comments below that describe the tests performed.
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has developer documentation been updated if required?

### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by DominicOram** [comment]
After discussion I will remove the binding for F1 to allow it to be used for help in the future.

**Comment by DominicOram** [comment]
On even further discussion we should actually use letters rather than function keys.

**Comment by DominicOram** [comment]
Now uses Shift + Alt and underlined letter to switch perspective. Documentation also added to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Adding-a-Button-to-the-Perspective-Switcher

**Comment by AdrianPotter** [comment]
- [ ] Please add some manual system tests for the shortcut keys
- [ ] Add release notes

**Comment by AdrianPotter** [comment]
- [ ] No underline on 'A' of alarms
- [ ] No underline on 'D' of DAE

**Comment by AdrianPotter** [comment]
- [ ] Sorry, this one might be a pain. In the menu, the underlines only appear when `alt` is pressed. On the perspective, they are constant. One problem with this is that when I press `alt` then `shift`, it is unclear what the shortcut `S` does because both the scripting perspective and Synoptic menu item are indicated. Can this be resolved?

**Comment by AdrianPotter** [comment]
- [ ] Console log in the help menu has no underline

**Comment by DominicOram** [comment]
Manual system tests 27-1 & 27-2 have been added.
I've looked into how to fix the other issues and because the behaviour of underlining the letters is inbuilt to Eclipse/SWT it's very had to customise. The proper solution may have to be to redo all the perspective buttons as our own custom widget rather than CLabels. This will be a large amount of work and should probably be done as it's own ticket. Can I suggest removing all the underlining from the buttons and instead add a list of what the key bindings are in the help dialog?

**Comment by DominicOram** [comment]
Scratch what I previously commented, new commit should fix all the above, even if it is a little bit of a fudge...

**Comment by AdrianPotter** [comment]
Thanks. The side bar shortcuts are great. Still a couple of minor things. All are missing underscores for the top navigation bar:

- [ ] Preferences
- [ ] Preferences sub-items
- [ ] Help
- [ ] Help/console log

Notably the top two are new and so were probably missed on their original ticket.

**Pull request merged**
