### PR TITLE
Ticket 6233: Use RAW requests on the log plotter data

### PR DESCRIPTION
**Pull request by DominicOram**
### Description of work

When sufficiently zoomed out the databrowser averages data to save memory. Additionally, when it has no data it will assume the data stays constant, in the example linked in the ticket it averaged the data just before getting no data for a long period of time and so it assumed this average was the value for that time. This changes any added PVs to `RAW` mode, stopping the averaging

As the user zooms in this averaging should correct itself but it didn't seem to be doing this very well, I'm not sure why.

### Ticket

See https://github.com/ISISComputingGroup/IBEX/issues/6233
Also https://github.com/ISISComputingGroup/IBEX/issues/2177

### System tests

I can't think of an easy way to test this

---

#### Code Review

- [x] Is the code of an acceptable quality?
- [x] Do the changes function as described and is it robust?
- [x] Is there associated PR for the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)?

### Final Steps
- [ ] Reviewer has also merged the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)

### CODE REVIEW

**Comment by John-Holt-Tessella** [comment]
Would it be possible to add a manual system test? Or is that too hard

**Comment by DominicOram** [comment]
Maybe, the issue is we need some data in the archive engine that will reliably produce the issue. We would then need a process for importing that data for the manual test.

**Comment by DominicOram** [comment]
Tested on NDXSCIDEMO, with no plots:
New GUI, no plots
with 5 plots pointing at motors POLREF, each covering a 3 month period:
New GUI, 5 plots
Doesn't seem to be notable memory concerns but GUI is still on SCIDEMO under C:\Instrument\gui_for_6233 if reviewer wants to test more.

**Comment by DominicOram** [comment]
On reflection I think it's too tricky to write tests for this but can discuss with reviewer

**Review by KathrynBaker — APPROVED** [review]

**Pull request merged**
